name: shell command
on: push
workflow dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-step2
        run: |
          echo "github action"
          echo "goodbye"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        npm install
        npm test
      